add Ambermoon.net, a remake of Ambermoon
opengaming/osgameclones pull request #1360
Opened 2021-07-17 17:04 UTC by kparal

Please note, while I used `content: free`, because the content is bundled in the release archive and free for the user, I believe the author actually uses the original assets from Ambermoon, i.e. most probably copyrighted content. I assume they are relying on its abandonware status and take the liberty to distribute it. I'm not sure if the `content` field should be changed to `commercial` or not.

2021-07-18 05:20 UTC, cxong requested changes

2021-07-18 05:20 UTC, cxong commented on games/a.yaml
> +  content: free
```suggestion
  content: commercial
```
since abandonware isn't a license

2021-07-18 05:20 UTC, cxong commented on games/a.yaml
> +    - 'C#'
```suggestion
    - C#
    framework:
    - .NET
```

2021-07-18 16:10 UTC, kparal commented
Updated per review.

2021-07-20 00:57 UTC, cxong approved these changes

2021-07-25 18:13 UTC, kparal commented
What is the next step now?

2021-07-25 23:04 UTC, merged