Add Signus: The Artefact Wars
opengaming/osgameclones pull request #1524
Opened 2021-11-12 19:55 UTC by nextghost

Signus: The Artefact Wars is a Czech turn-based strategy wargame originally released in 1998. The original developers have open-sourced the game on SourceForge back in 2002 and I've finished porting it to Linux and modern Windows earlier this year.

The game has no official website and the only Wikipedia page about it is in Czech so the "official" URL points to a fan website with some English content.

2021-11-14 05:32 UTC, cxong requested changes

2021-11-14 05:32 UTC, cxong commented on originals/s.yaml
> +    themes:
```suggestion
    theme:
```

2021-11-14 05:32 UTC, cxong commented on games/s.yaml
> +  lang: C++
```suggestion
  lang: C++
  framework:
  - SDL2
```

2021-11-14 22:14 UTC, cxong requested changes

2021-11-14 22:14 UTC, cxong commented on games/s.yaml
> +  lang: C++
```suggestion
  lang:
  - C++
```

2021-11-14 22:14 UTC, cxong commented on games/s.yaml
> +  license: GPL2
```suggestion
  license:
  - GPL2
```

2021-11-15 20:02 UTC, nextghost commented
I've fixed the `lang` and `license` structures, squashed the whole PR into a single commit and rebased it on current master.

2021-11-15 23:50 UTC, cxong approved these changes

2021-11-22 11:22 UTC, merged