Adding 2 projects for the game Lego Universe
opengaming/osgameclones pull request #1619
Opened 2022-02-16 02:18 UTC by MajickTek

This pull request adds the 2 largest open-source projects emulating [Lego Universe](https://en.wikipedia.org/wiki/Lego_Universe), a NetDevil MMORPG released in 2010.

These 2 projects have decently-sized communities and both are almost 100% functionally equivalent to the original game.

2022-02-16 02:23 UTC, MajickTek commented
Hmm the bot says format issues exist and the youtube link is not recognized as valid.

If somebody could help me re-format the YAML that would be greatly appreciated.

2022-02-16 23:17 UTC, cxong requested changes

2022-02-16 23:17 UTC, cxong commented on games/d.yaml
> +  youtube: ZhzMy-o0ByM
```suggestion
    youtube: ZhzMy-o0ByM
```

2022-02-17 05:11 UTC, cxong requested changes
need to add original game Lego Universe

2022-02-27 22:59 UTC, cxong requested changes

2022-02-27 22:59 UTC, cxong commented on games/d.yaml
> +  repo: 'https://github.com/DarkflameServer/DarkflameUniverse'
```suggestion
  repo: https://github.com/DarkflameUniverse/DarkflameServer
```

2022-02-27 22:59 UTC, cxong commented on games/u.yaml
> +  updated: '2022-02-15'
```suggestion
  updated: '2022-02-15'
  video:
    youtube: _b6HYmdcA8c
```

2022-03-05 09:35 UTC, merged