add spelling bee puzzle game
opengaming/osgameclones pull request #1816
Opened 2022-08-20 23:10 UTC by ConorSheehan1

2022-08-20 23:29 UTC, ConorSheehan1 commented
My bad, I see I need to add the original game too. Will update tomorrow

2022-08-21 23:13 UTC, cxong requested changes

2022-08-21 23:13 UTC, cxong commented on games/s.yaml
> +  content: free
```suggestion
```
I don't see any copyrightable content (art, music etc)

2022-08-21 23:13 UTC, cxong commented on games/s.yaml
> +  type: similar
```suggestion
  type: clone
```

2022-08-21 23:13 UTC, cxong commented on games/s.yaml
> +  - https://github.com/ConorSheehan1/spelling-bee/blob/main/.github/images/spelling-bee-dark.png
```suggestion
  - https://raw.githubusercontent.com/ConorSheehan1/spelling-bee/main/.github/images/spelling-bee.png
  - https://raw.githubusercontent.com/ConorSheehan1/spelling-bee/main/.github/images/spelling-bee-dark.png
```

2022-08-22 22:10 UTC, cxong approved these changes

2022-08-28 05:54 UTC, merged