Add Threes game & 2 clones
opengaming/osgameclones pull request #1970
Opened 2022-12-28 22:29 UTC by hendursaga

2022-12-29 21:57 UTC, cxong requested changes

2022-12-29 21:57 UTC, cxong commented on games/t.yaml
> +  updated: 2015-08-17
```suggestion
  updated: 2022-12-30
```

2022-12-29 21:57 UTC, cxong commented on games/t.yaml
> +  updated: 2016-08-20
```suggestion
  updated: 2022-12-30
```

2022-12-30 20:50 UTC, hendursaga commented
You can squash 'em all into one commit if you want.

2022-12-31 10:28 UTC, cxong approved these changes

2023-01-03 22:02 UTC, merged