Add Laser Kombat
opengaming/osgameclones pull request #2004
Opened 2023-01-30 16:42 UTC by sharkwouter

Laser Kombat is a very old Laser Kombat clone which I ported to SDL2.

2023-01-30 22:25 UTC, cxong requested changes

2023-01-30 22:25 UTC, cxong commented on games/l.yaml
> +  url: 'https://github.com/sharkwouter/laserkombat'
```suggestion
```
don't need this as it duplicates repo

2023-01-30 22:25 UTC, cxong commented on games/l.yaml
> +  development: active
```suggestion
  development: sporadic
```

2023-01-31 21:39 UTC, cxong approved these changes

2023-01-31 21:40 UTC, cxong commented on games/l.yaml
> +- name: Laser Kombat
please sort alphabetically (after ladder, before LastNinja)

2023-02-01 13:21 UTC, sharkwouter commented on games/l.yaml
> +- name: Laser Kombat
Oh, I missed ladder there. Fixed now, thanks!

2023-02-05 21:25 UTC, merged