Add OpenVic
opengaming/osgameclones pull request #2246
Opened 2023-08-28 17:01 UTC by basxto

It’s in an very early stage.

2023-08-28 17:14 UTC, basxto commented
It would make sense to also add `Grand Strategy` for these kinds of games, but I’m not sure where that would belong.

2023-08-29 01:01 UTC, cxong requested changes

2023-08-29 01:01 UTC, cxong commented on originals/v.yaml
> +    wikipedia: 'https://en.wikipedia.org/wiki/Victoria_II'
```suggestion
    wikipedia: Victoria II
```

2023-08-29 01:01 UTC, cxong commented on originals/v.yaml
> +  - victoria 2
```suggestion
  - Victoria 2
```

2023-09-03 23:07 UTC, merged